In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import time

def capVideo(video_path, name_video):
    cap = cv2.VideoCapture(video_path)

    width  = int(cap.get(3)) # float
    height = int(cap.get(4)) # float
    # it gives me 0.0 :/
    fps = cap.get(cv2.CAP_PROP_FPS)
    
    out = cv2.VideoWriter(name_video, -1, fps, (width,height))
    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret == True: 
            img_out = edge_detection(frame)
#             out.write(img_out)
            cv2.imshow('frame',img_out)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
        else:
            break 

    cap.release()
    cv2.destroyAllWindows()
    
def edge_detection(im):
    im_original = im.copy()

    # PYR MEAN SHIFT FILTERING
    # https://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html?highlight=meanshiftfiltering#pyrmeanshiftfiltering
    # I read a bit of Paper http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.76.8968&rep=rep1&type=pdf
    im = cv2.pyrMeanShiftFiltering(im, sp = 2, sr = 8, maxLevel = 3)

    # Try to search pixel's values which correspond at the wall and I try to remove these
    for c in range(im.shape[2]):
        mean_value = np.average(im[:, :, c])
        im[:, :, c] = np.where(im[:, :, c] > mean_value, 255 , 0)

    # Canny
    im = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
#     im = cv2.Canny(im, threshold1 = 50, threshold2 = 150, apertureSize = 3, L2gradient = True)
    im = cv2.Canny(im, 50, 240)
    # Lines
    im_lines = np.copy(im_original)
    minLineLength = 50
    maxLineGap = 5
    lines = cv2.HoughLinesP(im, 1,  np.pi / 180, 10, minLineLength, maxLineGap)
    if len(lines) > 0:
        for x in range(0, len(lines)):
            for x1, y1, x2, y2 in lines[x]:
                cv2.line(im_lines, (x1, y1), (x2, y2), (255, 0, 0), 4)
    return im_lines

In [6]:
import os
for forder in os.listdir("../Project-material-3/videos"):
    if forder == '.DS_Store':
        continue
    path=os.path.join("../Project-material-3/videos", forder)
    for file in os.listdir(path):
#         if file.endswith(".mp4") or file.endswith(".MP4"):
        if file.endswith(".MOV"):
            video=os.path.join(path, file)
            print(forder+'/'+file)
            capVideo(video, 'results/' + forder + '/' + file)

004/IMG_3809.MOV
004/IMG_3812.MOV
004/IMG_3815.MOV
004/IMG_3816.MOV
006/IMG_9620.MOV
009/IMG_2653.MOV
009/IMG_2657.MOV
009/IMG_2658.MOV
009/IMG_2660.MOV
012/IMG_4079.MOV
012/IMG_4080.MOV


In [ ]:
start = time.time()
capVideo('../Project-material-3/videos/000/VIRB0406.MP4', 'VIRB0406.MP4')
end = time.time()
print(end - start)

In [64]:
x = np.arange(12).reshape(2,3,2)
# x = np.array([
#         [ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8],
#         [ 9, 10, 11]])
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [65]:
np.argwhere(x)

array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 2, 0],
       [0, 2, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 2, 0],
       [1, 2, 1]])

In [63]:
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [3, 0],
       [3, 1],
       [3, 2]])

In [68]:
x = np.array([
        [ 2,  2,  2],
        [ 2,  2,  2],
        [ 2,  2,  2],
        [ 2,  2,  2]])

In [69]:
y = np.array([
        [ 4,  4,  4],
        [ 4,  4,  4],
        [ 4,  4,  4],
        [ 4,  4,  4]])

In [75]:
import numpy as np 

In [81]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
np.argmax(a, axis=0)

array([2, 2, 2, 2])

In [84]:
np.argmin(a, axis=0)

array([0, 0, 0, 0])

In [87]:
a = np.arange(10)

In [90]:
np.clip(a, 1, 5)

array([1, 1, 2, 3, 4, 5, 5, 5, 5, 5])